window.APP_CONFIG = {
  LLM_URL:           "${FRONTEND_LLM_URL}",
  LLM_MODEL:         "${FRONTEND_LLM_MODEL}",
  MINIO_BASE:        "${FRONTEND_MINIO_BASE}",
  EXTRACT_API:       "${FRONTEND_EXTRACT_API}",
  EXTRACT_PHOTOS:    ${FRONTEND_EXTRACT_PHOTOS},
  PHOTO_MAX_INDEX:   ${PHOTO_MAX_INDEX},
  GPS_RADIUS_METERS: ${GPS_RADIUS_METERS},
  DATE_TOLERANCE_DAYS: ${DATE_TOLERANCE_DAYS}
};
